[package]
name = "aoc3"
version = "0.1.0"
authors = ["Roberto Amorim <roberto.amorim@superbuy.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
